{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## **Import**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import subprocess\n",
    "from dotenv import load_dotenv\n",
    "import os"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## **Input Parameters**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cargar variables desde .env\n",
    "load_dotenv()\n",
    "\n",
    "# Obtener los valores\n",
    "SOURCE_USER = os.getenv(\"SOURCE_DB_USER\")\n",
    "SOURCE_PASSWORD = os.getenv(\"SOURCE_DB_PASSWORD\")\n",
    "SOURCE_HOST = os.getenv(\"SOURCE_DB_HOST\")\n",
    "SOURCE_PORT = os.getenv(\"SOURCE_DB_PORT\")\n",
    "SOURCE_DATABASE = os.getenv(\"SOURCE_DB_NAME\")\n",
    "\n",
    "TARGET_USER = os.getenv(\"TARGET_DB_USER\")\n",
    "TARGET_PASSWORD = os.getenv(\"TARGET_DB_PASSWORD\")\n",
    "TARGET_HOST = os.getenv(\"TARGET_DB_HOST\")\n",
    "TARGET_PORT = os.getenv(\"TARGET_DB_PORT\")\n",
    "TARGET_DATABASE = os.getenv(\"TARGET_DB_NAME\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## **Functions**"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## **Process**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hubo un error al ejecutar pg_dump: Command '['pg_dump', '--dbname=postgresql://postgres:mypersonalpassword@localhost:5432/postgres', '--file=backup.sql']' returned non-zero exit status 1.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "pg_dump: error: connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n"
     ]
    }
   ],
   "source": [
    "# Comando pg_dump\n",
    "command = [\n",
    "    \"pg_dump\",\n",
    "    f\"--dbname=postgresql://{SOURCE_USER}:{SOURCE_PASSWORD}@{SOURCE_HOST}:{SOURCE_PORT}/{SOURCE_DATABASE}\",\n",
    "    f\"--file=backup.sql\"\n",
    "]\n",
    "\n",
    "# Ejecutar el comando\n",
    "try:\n",
    "    subprocess.run(command, check=True)\n",
    "    print(\"Volcado de base de datos realizado con Ã©xito\")\n",
    "except subprocess.CalledProcessError as e:\n",
    "    print(f\"Hubo un error al ejecutar pg_dump: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "dw-for-bi-course-env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
